import React, { useState } from 'react';

interface OrganizationLogoProps {
  organizationName: string;
  logoUrl?: string | null;
  size?: 'sm' | 'md' | 'lg' | 'xl' | '2xl';
  className?: string;
}

// Organization name to logo filename mapping
export const organizationLogos: Record<string, string> = {
  // National Agencies
  'Bpifrance': '/logos/bpifrance-official.png',
  'ADEME': '/logos/ademe-official.png',
  'Ademe': '/logos/ademe.png',
  'Pôle emploi': '/logos/france-travail-official.png',
  'France Travail': '/logos/france-travail-official.png',
  'France Travail (Pôle emploi)': '/logos/france-travail.png',
  'Banque des Territoires': '/logos/banque-des-territoires.png',
  'La Banque des Territoires': '/logos/banque-des-territoires.png',
  'ANAH': '/logos/anah.png',
  'Agence nationale de l\'habitat': '/logos/anah.png',
  'Agence Nationale de l\'Habitat (ANAH)': '/logos/anah.png',
  'AFD': '/logos/afd.png',
  'Agence Française de Développement': '/logos/afd.png',
  'Agence Française de Développement (AFD)': '/logos/afd.png',
  'Action Logement': '/logos/action-logement.png',
  'Action Logement Services': '/logos/action-logement.png',
  'ADIE': '/logos/adie.png',
  'Association pour le Droit à l\'Initiative Economique (ADIE)': '/logos/adie.png',
  'Association pour le Droit à l\'Initiative Economique': '/logos/adie.png',
  'AGEFIPH': '/logos/agefiph.png',
  'AGEFIPH Provence-Alpes-Céte d\'Azur et Corse': '/logos/agefiph.png',
  'Association de Gestion du Fonds pour l\'Insertion Professionnelle des Personnes Handicapées': '/logos/agefiph.png',
  'France Num': '/logos/france-num.png',
  'FranceNum': '/logos/france-num.png',
  'ANCT': '/logos/anct.png',
  'Agence nationale de la cohésion des territoires': '/logos/anct.png',
  'Agence nationale de la cohésion des territoires (ANCT)': '/logos/anct.png',
  'ASP': '/logos/asp.png',
  'Agence de services et de paiement': '/logos/asp.png',
  'Agence de services et de paiement (ASP)': '/logos/asp.png',
  'France Agrimer': '/logos/france-agrimer.png',
  'FranceAgrimer': '/logos/france-agrimer.png',
  'FranceAgriMer': '/logos/france-agrimer.png',
  'France AgriMer': '/logos/france-agrimer.png',
  'FRANCEAGRIMER': '/logos/france-agrimer.png',
  'Caisse des Dépôts': '/logos/caisse-des-depots.png',
  'Caisse des Dépôts et Consignations': '/logos/caisse-des-depots.png',
  'État': '/logos/republique-francaise.png',
  'République française': '/logos/republique-francaise.png',
  'Gouvernement': '/logos/republique-francaise.png',
  'DRAAF': '/logos/draaf.png',
  'Direction régionale de l\'alimentation, de l\'agriculture et de la forêt': '/logos/draaf.png',
  'Cerema': '/logos/cerema.png',
  'Centre d\'études et d\'expertise sur les risques, l\'environnement, la mobilité et l\'aménagement': '/logos/cerema.png',
  'CCI France': '/logos/cci-france.png',
  'Chambre de Commerce et d\'Industrie France': '/logos/cci-france.png',
  'Chambres de Commerce et d\'Industrie': '/logos/cci-france.png',
  'CMA France': '/logos/cma-france.png',
  'Chambre de Métiers et de l\'Artisanat': '/logos/cma-france.png',
  'Chambres de Métiers et de l\'Artisanat de France': '/logos/cma-france.png',
  'DREAL': '/logos/dreal.png',
  'Direction régionale de l\'environnement, de l\'aménagement et du logement': '/logos/dreal.png',
  'Programme LEADER': '/logos/programme-leader.jpg',
  'LEADER': '/logos/programme-leader.jpg',
  'Carsat': '/logos/carsat.jpeg',
  'Carsat (Assurance Retraite et Santé au Travail)': '/logos/carsat.jpeg',
  'CARSAT': '/logos/carsat.jpeg',
  'URSSAF': '/logos/urssaf.jpg',
  'Urssaf': '/logos/urssaf.jpg',
  'Union de Recouvrement des cotisations de Sécurité Sociale et d\'Allocations Familiales': '/logos/urssaf.jpg',

  // European Union
  'Union Européenne': '/logos/union-europeenne.png',
  'Union européenne': '/logos/union-europeenne.png',
  'European Union': '/logos/union-europeenne.png',
  'Europe': '/logos/union-europeenne.png',
  'FEDER': '/logos/union-europeenne.png',
  'Fonds européen de développement régional': '/logos/union-europeenne.png',
  'FSE': '/logos/union-europeenne.png',
  'Fonds social européen': '/logos/union-europeenne.png',
  'FEADER': '/logos/union-europeenne.png',
  'Fonds européen agricole pour le développement rural': '/logos/union-europeenne.png',

  // Social Security & Family Benefits
  'CAF': '/logos/caf.png',
  'Caisse d\'Allocations Familiales': '/logos/caf.png',
  'Caisse d\'allocations familiales': '/logos/caf.png',
  'CNAF': '/logos/caf.png',
  'Caisse Nationale des Allocations Familiales': '/logos/caf.png',
  'Allocations Familiales': '/logos/caf.png',
  'MSA': '/logos/msa.png',
  'Mutualité Sociale Agricole': '/logos/msa.png',
  'Mutualité sociale agricole': '/logos/msa.png',
  'Assurance Maladie': '/logos/assurance-maladie.png',
  'CPAM': '/logos/assurance-maladie.png',
  'Caisse Primaire d\'Assurance Maladie': '/logos/assurance-maladie.png',
  'CNAM': '/logos/assurance-maladie.png',
  'Caisse Nationale d\'Assurance Maladie': '/logos/assurance-maladie.png',
  'Ameli': '/logos/assurance-maladie.png',

  // Sports
  'ANS': '/logos/ans.jpg',
  'Agence nationale du Sport': '/logos/ans.jpg',
  'Agence Nationale du Sport': '/logos/ans.jpg',
  'Agence nationale du sport': '/logos/ans.jpg',

  // Entrepreneur Networks
  'BGE': '/logos/bge.png',
  'BGE Réseau': '/logos/bge.png',
  'BGE - Appui aux entrepreneurs': '/logos/bge.png',
  'Initiative France': '/logos/initiative-france.png',
  'Initiative': '/logos/initiative-france.png',
  'Réseau Initiative': '/logos/initiative-france.png',
  'Réseau Entreprendre': '/logos/reseau-entreprendre.svg',
  'Reseau Entreprendre': '/logos/reseau-entreprendre.svg',
  'France Active': '/logos/france-active.png',
  'FranceActive': '/logos/france-active.png',
  'Réseau France Active': '/logos/france-active.png',

  // France 2030 & Investment Programs
  'France 2030': '/logos/france-2030.webp',
  'France2030': '/logos/france-2030.webp',
  'PIA': '/logos/france-2030.webp',
  'Programme d\'Investissements d\'Avenir': '/logos/france-2030.webp',
  'Investissements d\'Avenir': '/logos/france-2030.webp',

  // Environment & Biodiversity
  'OFB': '/logos/ofb.svg',
  'Office français de la biodiversité': '/logos/ofb.svg',
  'Office Français de la Biodiversité': '/logos/ofb.svg',

  // Retirement & Pension
  'CNAV': '/logos/cnav.png',
  'Caisse Nationale d\'Assurance Vieillesse': '/logos/cnav.png',
  'Caisse nationale d\'assurance vieillesse': '/logos/cnav.png',
  'Assurance Retraite': '/logos/cnav.png',

  // Work Conditions
  'ANACT': '/logos/anact.webp',
  'Anact': '/logos/anact.webp',
  'Agence nationale pour l\'amélioration des conditions de travail': '/logos/anact.webp',
  'Agence Nationale pour l\'Amélioration des Conditions de Travail': '/logos/anact.webp',

  // Government Services (use République Française logo)
  'DREETS': '/logos/republique-francaise.png',
  'Direction régionale de l\'économie, de l\'emploi, du travail et des solidarités': '/logos/republique-francaise.png',
  'Préfecture': '/logos/republique-francaise.png',
  'Prefecture': '/logos/republique-francaise.png',
  'Services de l\'État': '/logos/republique-francaise.png',
  'FNADT': '/logos/republique-francaise.png',
  'Fonds national d\'aménagement et de développement du territoire': '/logos/republique-francaise.png',
  'DIRECCTE': '/logos/republique-francaise.png',
  'DDT': '/logos/republique-francaise.png',
  'DDTM': '/logos/republique-francaise.png',

  // Water Agencies
  'Agence de l\'eau Rhin-Meuse': '/logos/agence-eau-rhin-meuse.png',
  'Agence de l\'eau  Rhin-Meuse': '/logos/agence-eau-rhin-meuse.png',
  'Agence de l\'Eau Loire-Bretagne': '/logos/agence-eau-loire-bretagne.png',
  'Agence de l\'eau Loire-Bretagne': '/logos/agence-eau-loire-bretagne.png',
  'Agence de l\'eau Adour-Garonne': '/logos/agence-eau-adour-garonne.png',
  'Agence de l\'eau Adour Garonne': '/logos/agence-eau-adour-garonne.png',
  'Agence de l\'eau Artois - Picardie': '/logos/agence-eau-artois-picardie.png',
  'Agence de l\'eau Artois-Picardie': '/logos/agence-eau-artois-picardie.png',
  'Agence de l\'eau Artois Picardie': '/logos/agence-eau-artois-picardie.png',
  'Agence de l\'eau Rhône-Méditerranée-Corse': '/logos/agence-eau-rhone-mediterranee-corse.png',
  'Agence de l\'eau Rhône Méditerranée Corse': '/logos/agence-eau-rhone-mediterranee-corse.png',
  'Agence de l\'eau Seine Normandie': '/logos/agence-eau-seine-normandie.png',
  'Agence de l\'eau Seine-Normandie': '/logos/agence-eau-seine-normandie.png',

  // Regions
  'Région Auvergne-Rhône-Alpes': '/logos/region-auvergne-rhone-alpes.png',
  'Auvergne-Rhône-Alpes': '/logos/region-auvergne-rhone-alpes.png',
  'Conseil régional Auvergne-Rhône-Alpes': '/logos/region-auvergne-rhone-alpes.png',
  'Conseil régional d\'Auvergne-Rhône-Alpes': '/logos/region-auvergne-rhone-alpes.png',
  'Région Bourgogne Franche-Comté': '/logos/region-bourgogne-franche-comte.png',
  'Région Bourgogne-Franche-Comté': '/logos/region-bourgogne-franche-comte.png',
  'Bourgogne Franche-Comté': '/logos/region-bourgogne-franche-comte.png',
  'Bourgogne-Franche-Comté': '/logos/region-bourgogne-franche-comte.png',
  'Conseil régional de Bourgogne Franche-Comté': '/logos/region-bourgogne-franche-comte.png',
  'Conseil régional de Bourgogne-Franche-Comté': '/logos/region-bourgogne-franche-comte.png',
  'Région Normandie': '/logos/region-normandie.png',
  'Normandie': '/logos/region-normandie.png',
  'Conseil régional de Normandie': '/logos/region-normandie.png',
  'Région Nouvelle-Aquitaine': '/logos/region-nouvelle-aquitaine.png',
  'Nouvelle-Aquitaine': '/logos/region-nouvelle-aquitaine.png',
  'Conseil régional de Nouvelle-Aquitaine': '/logos/region-nouvelle-aquitaine.png',
  'Région Provence-Alpes-Côte d\'Azur': '/logos/region-paca.png',
  'Provence-Alpes-Côte d\'Azur': '/logos/region-paca.png',
  'Conseil régional de Provence-Alpes-Côte d\'Azur': '/logos/region-paca.png',
  'Région Sud': '/logos/region-paca.png',
  'Région Sud Provence-Alpes-Côte d\'Azur': '/logos/region-paca.png',
  'Sud Provence-Alpes-Côte d\'Azur': '/logos/region-paca.png',
  'Conseil régional Sud': '/logos/region-paca.png',
  'Conseil régional de la Région Sud': '/logos/region-paca.png',
  'Région Réunion': '/logos/region-reunion.png',
  'Réunion': '/logos/region-reunion.png',
  'Conseil régional de La Réunion': '/logos/region-reunion.png',
  'Région Île-de-France': '/logos/region-ile-de-france.png',
  'Île-de-France': '/logos/region-ile-de-france.png',
  'Ile-de-France': '/logos/region-ile-de-france.png',
  'Conseil régional d\'Île-de-France': '/logos/region-ile-de-france.png',
  'Conseil régional d\'Ile de France': '/logos/region-ile-de-france.png',
  'Région Bretagne': '/logos/region-bretagne.png',
  'Bretagne': '/logos/region-bretagne.png',
  'Conseil régional de Bretagne': '/logos/region-bretagne.png',
  'Région Centre-Val de Loire': '/logos/region-centre-val-de-loire.png',
  'Centre-Val de Loire': '/logos/region-centre-val-de-loire.png',
  'Conseil régional du Centre-Val de Loire': '/logos/region-centre-val-de-loire.png',
  'Région Corse': '/logos/region-corse.png',
  'Corse': '/logos/region-corse.png',
  'Conseil régional de Corse': '/logos/region-corse.png',
  'Région Grand Est': '/logos/region-grand-est.png',
  'Grand Est': '/logos/region-grand-est.png',
  'Conseil régional du Grand Est': '/logos/region-grand-est.png',
  'Conseil régional Grand Est': '/logos/region-grand-est.png',
  'Région Guadeloupe': '/logos/region-guadeloupe.png',
  'Guadeloupe': '/logos/region-guadeloupe.png',
  'Conseil régional de Guadeloupe': '/logos/region-guadeloupe.png',
  'Région Guyane': '/logos/region-guyane.png',
  'Guyane': '/logos/region-guyane.png',
  'Conseil régional de Guyane': '/logos/region-guyane.png',
  'Région Hauts-de-France': '/logos/region-hauts-de-france.png',
  'Hauts-de-France': '/logos/region-hauts-de-france.png',
  'Conseil régional des Hauts-de-France': '/logos/region-hauts-de-france.png',
  'Région Martinique': '/logos/region-martinique.png',
  'Martinique': '/logos/region-martinique.png',
  'Conseil régional de Martinique': '/logos/region-martinique.png',
  'Région Mayotte': '/logos/region-mayotte.png',
  'Mayotte': '/logos/region-mayotte.png',
  'Conseil régional de Mayotte': '/logos/region-mayotte.png',
  'Région Occitanie': '/logos/region-occitanie.png',
  'Occitanie': '/logos/region-occitanie.png',
  'Conseil régional d\'Occitanie': '/logos/region-occitanie.png',
  'Région Pays de la Loire': '/logos/region-pays-de-la-loire.png',
  'Pays de la Loire': '/logos/region-pays-de-la-loire.png',
  'Conseil régional des Pays de la Loire': '/logos/region-pays-de-la-loire.png',

  // Local organizations
  'CC de la Plaine de l\'Ain': '/logos/cc-plaine-ain.png',
  'Communauté de Communes de la Plaine de l\'Ain': '/logos/cc-plaine-ain.png',
  'Communauté de Communes Pays de Mormal': '/logos/cc-pays-mormal.png',
  'Communauté de communes du Pays de Mormal': '/logos/cc-pays-mormal.png',
  'Agence de Développement Economique de la Corse': '/logos/agence-dev-economique-corse.png',
  'Chambre de Commerce et d\'Industrie de la région Hauts de France': '/logos/cci-hauts-de-france.png',
  'Clermont Auvergne Métropole': '/logos/clermont-auvergne-metropole.png',
  'Brest Métropole': '/logos/brest-metropole.png',
  'Brest métropole': '/logos/brest-metropole.png',
  'Communauté de Communes des 7 Vallées': '/logos/communaute-communes-generic.png',
  'Communauté de Communes du Bazadais': '/logos/communaute-communes-generic.png',
  'Communauté de Communes du Saulnois': '/logos/communaute-communes-generic.png',

  // Départements
  'Département Ain': '/logos/dept-01.png',
  'Département de l\'Ain': '/logos/dept-01.png',
  'Conseil départemental de l\'Ain': '/logos/dept-01.png',
  'Département 01 - Ain': '/logos/dept-01.png',
  'Département Aisne': '/logos/dept-02.svg',
  'Département de l\'Aisne': '/logos/dept-02.svg',
  'Conseil départemental de l\'Aisne': '/logos/dept-02.svg',
  'Département 02 - Aisne': '/logos/dept-02.svg',
  'Département Allier': '/logos/dept-03.jpg',
  'Département de l\'Allier': '/logos/dept-03.jpg',
  'Conseil départemental de l\'Allier': '/logos/dept-03.jpg',
  'Département 03 - Allier': '/logos/dept-03.jpg',
  'Département Alpes-de-Haute-Provence': '/logos/dept-04.png',
  'Département des Alpes-de-Haute-Provence': '/logos/dept-04.png',
  'Conseil départemental des Alpes-de-Haute-Provence': '/logos/dept-04.png',
  'Département 04 - Alpes-de-Haute-Provence': '/logos/dept-04.png',
  'Département Hautes-Alpes': '/logos/dept-05.png',
  'Département des Hautes-Alpes': '/logos/dept-05.png',
  'Conseil départemental des Hautes-Alpes': '/logos/dept-05.png',
  'Département 05 - Hautes-Alpes': '/logos/dept-05.png',
  'Département Alpes-Maritimes': '/logos/dept-06.png',
  'Département des Alpes-Maritimes': '/logos/dept-06.png',
  'Conseil départemental des Alpes-Maritimes': '/logos/dept-06.png',
  'Département 06 - Alpes-Maritimes': '/logos/dept-06.png',
  'Département Ardèche': '/logos/dept-07.png',
  'Département de l\'Ardèche': '/logos/dept-07.png',
  'Conseil départemental de l\'Ardèche': '/logos/dept-07.png',
  'Département 07 - Ardèche': '/logos/dept-07.png',
  'Département Ardennes': '/logos/dept-08.png',
  'Département des Ardennes': '/logos/dept-08.png',
  'Conseil départemental des Ardennes': '/logos/dept-08.png',
  'Département 08 - Ardennes': '/logos/dept-08.png',
  'Département Ariège': '/logos/dept-09.png',
  'Département de l\'Ariège': '/logos/dept-09.png',
  'Conseil départemental de l\'Ariège': '/logos/dept-09.png',
  'Département 09 - Ariège': '/logos/dept-09.png',
  'Département Aube': '/logos/dept-10.svg',
  'Département de l\'Aube': '/logos/dept-10.svg',
  'Conseil départemental de l\'Aube': '/logos/dept-10.svg',
  'Département 10 - Aube': '/logos/dept-10.svg',
  'Département Aude': '/logos/dept-11.png',
  'Département de l\'Aude': '/logos/dept-11.png',
  'Conseil départemental de l\'Aude': '/logos/dept-11.png',
  'Département 11 - Aude': '/logos/dept-11.png',
  'Département Aveyron': '/logos/dept-12.svg',
  'Département de l\'Aveyron': '/logos/dept-12.svg',
  'Conseil départemental de l\'Aveyron': '/logos/dept-12.svg',
  'Département 12 - Aveyron': '/logos/dept-12.svg',
  'Département Bouches-du-Rhône': '/logos/dept-13.svg',
  'Département des Bouches-du-Rhône': '/logos/dept-13.svg',
  'Conseil départemental des Bouches-du-Rhône': '/logos/dept-13.svg',
  'Département 13 - Bouches-du-Rhône': '/logos/dept-13.svg',
  'Département Calvados': '/logos/dept-14.png',
  'Département du Calvados': '/logos/dept-14.png',
  'Conseil départemental du Calvados': '/logos/dept-14.png',
  'Département 14 - Calvados': '/logos/dept-14.png',
  'Département Cantal': '/logos/dept-15.svg',
  'Département du Cantal': '/logos/dept-15.svg',
  'Conseil départemental du Cantal': '/logos/dept-15.svg',
  'Département 15 - Cantal': '/logos/dept-15.svg',
  'Département Charente': '/logos/dept-16.svg',
  'Département de la Charente': '/logos/dept-16.svg',
  'Conseil départemental de la Charente': '/logos/dept-16.svg',
  'Département 16 - Charente': '/logos/dept-16.svg',
  'Département Charente-Maritime': '/logos/dept-17.svg',
  'Département de la Charente-Maritime': '/logos/dept-17.svg',
  'Conseil départemental de la Charente-Maritime': '/logos/dept-17.svg',
  'Département 17 - Charente-Maritime': '/logos/dept-17.svg',
  'Département Cher': '/logos/dept-18.png',
  'Département du Cher': '/logos/dept-18.png',
  'Conseil départemental du Cher': '/logos/dept-18.png',
  'Département 18 - Cher': '/logos/dept-18.png',
  'Département Corrèze': '/logos/dept-19.png',
  'Département de la Corrèze': '/logos/dept-19.png',
  'Conseil départemental de la Corrèze': '/logos/dept-19.png',
  'Département 19 - Corrèze': '/logos/dept-19.png',
  'Département Côte-d\'Or': '/logos/dept-21.png',
  'Département de la Côte-d\'Or': '/logos/dept-21.png',
  'Conseil départemental de la Côte-d\'Or': '/logos/dept-21.png',
  'Département 21 - Côte-d\'Or': '/logos/dept-21.png',
  'Département Côtes-d\'Armor': '/logos/dept-22.svg',
  'Département des Côtes-d\'Armor': '/logos/dept-22.svg',
  'Conseil départemental des Côtes-d\'Armor': '/logos/dept-22.svg',
  'Département 22 - Côtes-d\'Armor': '/logos/dept-22.svg',
  'Département Creuse': '/logos/dept-23.png',
  'Département de la Creuse': '/logos/dept-23.png',
  'Conseil départemental de la Creuse': '/logos/dept-23.png',
  'Département 23 - Creuse': '/logos/dept-23.png',
  'Département Dordogne': '/logos/dept-24.svg',
  'Département de la Dordogne': '/logos/dept-24.svg',
  'Conseil départemental de la Dordogne': '/logos/dept-24.svg',
  'Département 24 - Dordogne': '/logos/dept-24.svg',
  'Département Doubs': '/logos/dept-25.png',
  'Département du Doubs': '/logos/dept-25.png',
  'Conseil départemental du Doubs': '/logos/dept-25.png',
  'Département 25 - Doubs': '/logos/dept-25.png',
  'Département Drôme': '/logos/dept-26.png',
  'Département de la Drôme': '/logos/dept-26.png',
  'Conseil départemental de la Drôme': '/logos/dept-26.png',
  'Département 26 - Drôme': '/logos/dept-26.png',
  'Département Eure': '/logos/dept-27.png',
  'Département de l\'Eure': '/logos/dept-27.png',
  'Conseil départemental de l\'Eure': '/logos/dept-27.png',
  'Département 27 - Eure': '/logos/dept-27.png',
  'Département Eure-et-Loir': '/logos/dept-28.png',
  'Département d\'Eure-et-Loir': '/logos/dept-28.png',
  'Conseil départemental d\'Eure-et-Loir': '/logos/dept-28.png',
  'Département 28 - Eure-et-Loir': '/logos/dept-28.png',
  'Département Finistère': '/logos/dept-29.png',
  'Département du Finistère': '/logos/dept-29.png',
  'Conseil départemental du Finistère': '/logos/dept-29.png',
  'Département 29 - Finistère': '/logos/dept-29.png',
  'Département Gard': '/logos/dept-30.svg',
  'Département du Gard': '/logos/dept-30.svg',
  'Conseil départemental du Gard': '/logos/dept-30.svg',
  'Département 30 - Gard': '/logos/dept-30.svg',
  'Département Haute-Garonne': '/logos/dept-31.svg',
  'Département de la Haute-Garonne': '/logos/dept-31.svg',
  'Conseil départemental de la Haute-Garonne': '/logos/dept-31.svg',
  'Département 31 - Haute-Garonne': '/logos/dept-31.svg',
  'Département Gers': '/logos/dept-32.png',
  'Département du Gers': '/logos/dept-32.png',
  'Conseil départemental du Gers': '/logos/dept-32.png',
  'Département 32 - Gers': '/logos/dept-32.png',
  'Département Gironde': '/logos/dept-33.png',
  'Département de la Gironde': '/logos/dept-33.png',
  'Conseil départemental de la Gironde': '/logos/dept-33.png',
  'Département 33 - Gironde': '/logos/dept-33.png',
  'Département Hérault': '/logos/dept-34.png',
  'Département de l\'Hérault': '/logos/dept-34.png',
  'Conseil départemental de l\'Hérault': '/logos/dept-34.png',
  'Département 34 - Hérault': '/logos/dept-34.png',
  'Département Ille-et-Vilaine': '/logos/dept-35.svg',
  'Département d\'Ille-et-Vilaine': '/logos/dept-35.svg',
  'Conseil départemental d\'Ille-et-Vilaine': '/logos/dept-35.svg',
  'Département 35 - Ille-et-Vilaine': '/logos/dept-35.svg',
  'Département Indre': '/logos/dept-36.png',
  'Département de l\'Indre': '/logos/dept-36.png',
  'Conseil départemental de l\'Indre': '/logos/dept-36.png',
  'Département 36 - Indre': '/logos/dept-36.png',
  'Département Indre-et-Loire': '/logos/dept-37.svg',
  'Département d\'Indre-et-Loire': '/logos/dept-37.svg',
  'Conseil départemental d\'Indre-et-Loire': '/logos/dept-37.svg',
  'Département 37 - Indre-et-Loire': '/logos/dept-37.svg',
  'Département Isère': '/logos/dept-38.svg',
  'Département de l\'Isère': '/logos/dept-38.svg',
  'Conseil départemental de l\'Isère': '/logos/dept-38.svg',
  'Département 38 - Isère': '/logos/dept-38.svg',
  'Département Jura': '/logos/dept-39.png',
  'Département du Jura': '/logos/dept-39.png',
  'Conseil départemental du Jura': '/logos/dept-39.png',
  'Département 39 - Jura': '/logos/dept-39.png',
  'Département Landes': '/logos/dept-40.png',
  'Département des Landes': '/logos/dept-40.png',
  'Conseil départemental des Landes': '/logos/dept-40.png',
  'Département 40 - Landes': '/logos/dept-40.png',
  'Département Loir-et-Cher': '/logos/dept-41.svg',
  'Département du Loir-et-Cher': '/logos/dept-41.svg',
  'Conseil départemental du Loir-et-Cher': '/logos/dept-41.svg',
  'Département 41 - Loir-et-Cher': '/logos/dept-41.svg',
  'Département Loire': '/logos/dept-42.jpg',
  'Département de la Loire': '/logos/dept-42.jpg',
  'Conseil départemental de la Loire': '/logos/dept-42.jpg',
  'Département 42 - Loire': '/logos/dept-42.jpg',
  'Département Haute-Loire': '/logos/dept-43.png',
  'Département de la Haute-Loire': '/logos/dept-43.png',
  'Conseil départemental de la Haute-Loire': '/logos/dept-43.png',
  'Département 43 - Haute-Loire': '/logos/dept-43.png',
  'Département Loire-Atlantique': '/logos/dept-44.svg',
  'Département de la Loire-Atlantique': '/logos/dept-44.svg',
  'Conseil départemental de la Loire-Atlantique': '/logos/dept-44.svg',
  'Département 44 - Loire-Atlantique': '/logos/dept-44.svg',
  'Département Loiret': '/logos/dept-45.png',
  'Département du Loiret': '/logos/dept-45.png',
  'Conseil départemental du Loiret': '/logos/dept-45.png',
  'Département 45 - Loiret': '/logos/dept-45.png',
  'Département Lot': '/logos/dept-46.png',
  'Département du Lot': '/logos/dept-46.png',
  'Conseil départemental du Lot': '/logos/dept-46.png',
  'Département 46 - Lot': '/logos/dept-46.png',
  'Département Lot-et-Garonne': '/logos/dept-47.png',
  'Département du Lot-et-Garonne': '/logos/dept-47.png',
  'Conseil départemental du Lot-et-Garonne': '/logos/dept-47.png',
  'Département 47 - Lot-et-Garonne': '/logos/dept-47.png',
  'Département Lozère': '/logos/dept-48.png',
  'Département de la Lozère': '/logos/dept-48.png',
  'Conseil départemental de la Lozère': '/logos/dept-48.png',
  'Département 48 - Lozère': '/logos/dept-48.png',
  'Département Maine-et-Loire': '/logos/dept-49.svg',
  'Département du Maine-et-Loire': '/logos/dept-49.svg',
  'Conseil départemental du Maine-et-Loire': '/logos/dept-49.svg',
  'Département 49 - Maine-et-Loire': '/logos/dept-49.svg',
  'Département Manche': '/logos/dept-50.png',
  'Département de la Manche': '/logos/dept-50.png',
  'Conseil départemental de la Manche': '/logos/dept-50.png',
  'Département 50 - Manche': '/logos/dept-50.png',
  'Département Marne': '/logos/dept-51.svg',
  'Département de la Marne': '/logos/dept-51.svg',
  'Conseil départemental de la Marne': '/logos/dept-51.svg',
  'Département 51 - Marne': '/logos/dept-51.svg',
  'Département Haute-Marne': '/logos/dept-52.png',
  'Département de la Haute-Marne': '/logos/dept-52.png',
  'Conseil départemental de la Haute-Marne': '/logos/dept-52.png',
  'Département 52 - Haute-Marne': '/logos/dept-52.png',
  'Département Mayenne': '/logos/dept-53.png',
  'Département de la Mayenne': '/logos/dept-53.png',
  'Conseil départemental de la Mayenne': '/logos/dept-53.png',
  'Département 53 - Mayenne': '/logos/dept-53.png',
  'Département Meurthe-et-Moselle': '/logos/dept-54.png',
  'Département de Meurthe-et-Moselle': '/logos/dept-54.png',
  'Conseil départemental de Meurthe-et-Moselle': '/logos/dept-54.png',
  'Département 54 - Meurthe-et-Moselle': '/logos/dept-54.png',
  'Département Meuse': '/logos/dept-55.svg',
  'Département de la Meuse': '/logos/dept-55.svg',
  'Conseil départemental de la Meuse': '/logos/dept-55.svg',
  'Département 55 - Meuse': '/logos/dept-55.svg',
  'Département Morbihan': '/logos/dept-56.svg',
  'Département du Morbihan': '/logos/dept-56.svg',
  'Conseil départemental du Morbihan': '/logos/dept-56.svg',
  'Département 56 - Morbihan': '/logos/dept-56.svg',
  'Département Moselle': '/logos/dept-57.png',
  'Département de la Moselle': '/logos/dept-57.png',
  'Conseil départemental de la Moselle': '/logos/dept-57.png',
  'Département 57 - Moselle': '/logos/dept-57.png',
  'Département Nièvre': '/logos/dept-58.png',
  'Département de la Nièvre': '/logos/dept-58.png',
  'Conseil départemental de la Nièvre': '/logos/dept-58.png',
  'Département 58 - Nièvre': '/logos/dept-58.png',
  'Département Nord': '/logos/dept-59.png',
  'Département du Nord': '/logos/dept-59.png',
  'Conseil départemental du Nord': '/logos/dept-59.png',
  'Département 59 - Nord': '/logos/dept-59.png',
  'Département Oise': '/logos/dept-60.png',
  'Département de l\'Oise': '/logos/dept-60.png',
  'Conseil départemental de l\'Oise': '/logos/dept-60.png',
  'Département 60 - Oise': '/logos/dept-60.png',
  'Département Orne': '/logos/dept-61.png',
  'Département de l\'Orne': '/logos/dept-61.png',
  'Conseil départemental de l\'Orne': '/logos/dept-61.png',
  'Département 61 - Orne': '/logos/dept-61.png',
  'Département Pas-de-Calais': '/logos/dept-62.svg',
  'Département du Pas-de-Calais': '/logos/dept-62.svg',
  'Conseil départemental du Pas-de-Calais': '/logos/dept-62.svg',
  'Département 62 - Pas-de-Calais': '/logos/dept-62.svg',
  'Département Puy-de-Dôme': '/logos/dept-63.png',
  'Département du Puy-de-Dôme': '/logos/dept-63.png',
  'Conseil départemental du Puy-de-Dôme': '/logos/dept-63.png',
  'Département 63 - Puy-de-Dôme': '/logos/dept-63.png',
  'Département Pyrénées-Atlantiques': '/logos/dept-64.png',
  'Département des Pyrénées-Atlantiques': '/logos/dept-64.png',
  'Conseil départemental des Pyrénées-Atlantiques': '/logos/dept-64.png',
  'Département 64 - Pyrénées-Atlantiques': '/logos/dept-64.png',
  'Département Hautes-Pyrénées': '/logos/dept-65.jpg',
  'Département des Hautes-Pyrénées': '/logos/dept-65.jpg',
  'Conseil départemental des Hautes-Pyrénées': '/logos/dept-65.jpg',
  'Département 65 - Hautes-Pyrénées': '/logos/dept-65.jpg',
  'Département Pyrénées-Orientales': '/logos/dept-66.png',
  'Département des Pyrénées-Orientales': '/logos/dept-66.png',
  'Conseil départemental des Pyrénées-Orientales': '/logos/dept-66.png',
  'Département 66 - Pyrénées-Orientales': '/logos/dept-66.png',
  'Département Bas-Rhin': '/logos/dept-67.svg',
  'Département du Bas-Rhin': '/logos/dept-67.svg',
  'Conseil départemental du Bas-Rhin': '/logos/dept-67.svg',
  'Département 67 - Bas-Rhin': '/logos/dept-67.svg',
  'Département Haut-Rhin': '/logos/dept-68.svg',
  'Département du Haut-Rhin': '/logos/dept-68.svg',
  'Conseil départemental du Haut-Rhin': '/logos/dept-68.svg',
  'Département 68 - Haut-Rhin': '/logos/dept-68.svg',
  'Département Rhône': '/logos/dept-69.png',
  'Département du Rhône': '/logos/dept-69.png',
  'Conseil départemental du Rhône': '/logos/dept-69.png',
  'Département 69 - Rhône': '/logos/dept-69.png',
  'Département Haute-Saône': '/logos/dept-70.png',
  'Département de la Haute-Saône': '/logos/dept-70.png',
  'Conseil départemental de la Haute-Saône': '/logos/dept-70.png',
  'Département 70 - Haute-Saône': '/logos/dept-70.png',
  'Département Saône-et-Loire': '/logos/dept-71.png',
  'Département de Saône-et-Loire': '/logos/dept-71.png',
  'Conseil départemental de Saône-et-Loire': '/logos/dept-71.png',
  'Département 71 - Saône-et-Loire': '/logos/dept-71.png',
  'Département Sarthe': '/logos/dept-72.png',
  'Département de la Sarthe': '/logos/dept-72.png',
  'Conseil départemental de la Sarthe': '/logos/dept-72.png',
  'Département 72 - Sarthe': '/logos/dept-72.png',
  'Département Savoie': '/logos/dept-73.png',
  'Département de la Savoie': '/logos/dept-73.png',
  'Conseil départemental de la Savoie': '/logos/dept-73.png',
  'Département 73 - Savoie': '/logos/dept-73.png',
  'Département Haute-Savoie': '/logos/dept-74.png',
  'Département de la Haute-Savoie': '/logos/dept-74.png',
  'Conseil départemental de la Haute-Savoie': '/logos/dept-74.png',
  'Département 74 - Haute-Savoie': '/logos/dept-74.png',
  'Département Paris': '/logos/dept-75.jpg',
  'Département de Paris': '/logos/dept-75.jpg',
  'Ville de Paris': '/logos/dept-75.jpg',
  'Département 75 - Paris': '/logos/dept-75.jpg',
  'Département Seine-Maritime': '/logos/dept-76.png',
  'Département de la Seine-Maritime': '/logos/dept-76.png',
  'Conseil départemental de la Seine-Maritime': '/logos/dept-76.png',
  'Département 76 - Seine-Maritime': '/logos/dept-76.png',
  'Département Seine-et-Marne': '/logos/dept-77.png',
  'Département de la Seine-et-Marne': '/logos/dept-77.png',
  'Conseil départemental de la Seine-et-Marne': '/logos/dept-77.png',
  'Département 77 - Seine-et-Marne': '/logos/dept-77.png',
  'Département Yvelines': '/logos/dept-78.png',
  'Département des Yvelines': '/logos/dept-78.png',
  'Conseil départemental des Yvelines': '/logos/dept-78.png',
  'Département 78 - Yvelines': '/logos/dept-78.png',
  'Département Deux-Sèvres': '/logos/dept-79.png',
  'Département des Deux-Sèvres': '/logos/dept-79.png',
  'Conseil départemental des Deux-Sèvres': '/logos/dept-79.png',
  'Département 79 - Deux-Sèvres': '/logos/dept-79.png',
  'Département Somme': '/logos/dept-80.png',
  'Département de la Somme': '/logos/dept-80.png',
  'Conseil départemental de la Somme': '/logos/dept-80.png',
  'Département 80 - Somme': '/logos/dept-80.png',
  'Département Tarn': '/logos/dept-81.jpg',
  'Département du Tarn': '/logos/dept-81.jpg',
  'Conseil départemental du Tarn': '/logos/dept-81.jpg',
  'Département 81 - Tarn': '/logos/dept-81.jpg',
  'Département Tarn-et-Garonne': '/logos/dept-82.svg',
  'Département du Tarn-et-Garonne': '/logos/dept-82.svg',
  'Conseil départemental du Tarn-et-Garonne': '/logos/dept-82.svg',
  'Département 82 - Tarn-et-Garonne': '/logos/dept-82.svg',
  'Département Var': '/logos/dept-83.png',
  'Département du Var': '/logos/dept-83.png',
  'Conseil départemental du Var': '/logos/dept-83.png',
  'Département 83 - Var': '/logos/dept-83.png',
  'Département Vaucluse': '/logos/dept-84.png',
  'Département du Vaucluse': '/logos/dept-84.png',
  'Conseil départemental du Vaucluse': '/logos/dept-84.png',
  'Département 84 - Vaucluse': '/logos/dept-84.png',
  'Département Vendée': '/logos/dept-85.svg',
  'Département de la Vendée': '/logos/dept-85.svg',
  'Conseil départemental de la Vendée': '/logos/dept-85.svg',
  'Département 85 - Vendée': '/logos/dept-85.svg',
  'Département Vienne': '/logos/dept-86.jpg',
  'Département de la Vienne': '/logos/dept-86.jpg',
  'Conseil départemental de la Vienne': '/logos/dept-86.jpg',
  'Département 86 - Vienne': '/logos/dept-86.jpg',
  'Département Haute-Vienne': '/logos/dept-87.svg',
  'Département de la Haute-Vienne': '/logos/dept-87.svg',
  'Conseil départemental de la Haute-Vienne': '/logos/dept-87.svg',
  'Département 87 - Haute-Vienne': '/logos/dept-87.svg',
  'Département Vosges': '/logos/dept-88.png',
  'Département des Vosges': '/logos/dept-88.png',
  'Conseil départemental des Vosges': '/logos/dept-88.png',
  'Département 88 - Vosges': '/logos/dept-88.png',
  'Département Yonne': '/logos/dept-89.png',
  'Département de l\'Yonne': '/logos/dept-89.png',
  'Conseil départemental de l\'Yonne': '/logos/dept-89.png',
  'Département 89 - Yonne': '/logos/dept-89.png',
  'Département Territoire de Belfort': '/logos/dept-90.png',
  'Département du Territoire de Belfort': '/logos/dept-90.png',
  'Conseil départemental du Territoire de Belfort': '/logos/dept-90.png',
  'Département 90 - Territoire de Belfort': '/logos/dept-90.png',
  'Département Essonne': '/logos/dept-91.png',
  'Département de l\'Essonne': '/logos/dept-91.png',
  'Conseil départemental de l\'Essonne': '/logos/dept-91.png',
  'Département 91 - Essonne': '/logos/dept-91.png',
  'Département Hauts-de-Seine': '/logos/dept-92.png',
  'Département des Hauts-de-Seine': '/logos/dept-92.png',
  'Conseil départemental des Hauts-de-Seine': '/logos/dept-92.png',
  'Département 92 - Hauts-de-Seine': '/logos/dept-92.png',
  'Département Seine-Saint-Denis': '/logos/dept-93.svg',
  'Département de la Seine-Saint-Denis': '/logos/dept-93.svg',
  'Conseil départemental de la Seine-Saint-Denis': '/logos/dept-93.svg',
  'Département 93 - Seine-Saint-Denis': '/logos/dept-93.svg',
  'Département Val-de-Marne': '/logos/dept-94.png',
  'Département du Val-de-Marne': '/logos/dept-94.png',
  'Conseil départemental du Val-de-Marne': '/logos/dept-94.png',
  'Département 94 - Val-de-Marne': '/logos/dept-94.png',
  'Département Val-d\'Oise': '/logos/dept-95.svg',
  'Département du Val-d\'Oise': '/logos/dept-95.svg',
  'Conseil départemental du Val-d\'Oise': '/logos/dept-95.svg',
  'Département 95 - Val-d\'Oise': '/logos/dept-95.svg',
  'Département Guadeloupe': '/logos/dept-971.png',
  'Département de la Guadeloupe': '/logos/dept-971.png',
  'Conseil départemental de la Guadeloupe': '/logos/dept-971.png',
  'Département 971 - Guadeloupe': '/logos/dept-971.png',
  'Département Martinique': '/logos/dept-972.png',
  'Département de la Martinique': '/logos/dept-972.png',
  'Conseil départemental de la Martinique': '/logos/dept-972.png',
  'Département 972 - Martinique': '/logos/dept-972.png',
  'Département Guyane': '/logos/dept-973.png',
  'Département de la Guyane': '/logos/dept-973.png',
  'Conseil départemental de la Guyane': '/logos/dept-973.png',
  'Département 973 - Guyane': '/logos/dept-973.png',
  'Département La Réunion': '/logos/dept-974.png',
  'Département de La Réunion': '/logos/dept-974.png',
  'Conseil départemental de La Réunion': '/logos/dept-974.png',
  'Département 974 - La Réunion': '/logos/dept-974.png',
  'Département Mayotte': '/logos/dept-976.png',
  'Département de Mayotte': '/logos/dept-976.png',
  'Conseil départemental de Mayotte': '/logos/dept-976.png',
  'Département 976 - Mayotte': '/logos/dept-976.png',
};

const OrganizationLogo: React.FC<OrganizationLogoProps> = ({
  organizationName,
  logoUrl,
  size = 'sm',
  className = ''
}) => {
  const [imageError, setImageError] = useState(false);
  const [imageLoading, setImageLoading] = useState(true);
  const [currentLogoSrc, setCurrentLogoSrc] = useState<string | null>(null);

  const sizeClasses = {
    sm: 'w-6 h-6',
    md: 'w-8 h-8',
    lg: 'w-12 h-12',
    xl: 'w-32 h-32',
    '2xl': 'w-48 h-48'
  };

  const textSizes = {
    sm: 'text-[10px]',
    md: 'text-xs',
    lg: 'text-sm',
    xl: 'text-2xl',
    '2xl': 'text-4xl'
  };

  // Three-tier logo source priority:
  // 1. Try database logo URL first (if provided)
  // 2. Fall back to static logo (if available)
  // 3. Show initials if both fail
  const staticLogo = organizationLogos[organizationName];
  const primaryLogoSrc = logoUrl || staticLogo;
  const fallbackLogoSrc = logoUrl && staticLogo ? staticLogo : null;

  // Set initial logo source
  React.useEffect(() => {
    setCurrentLogoSrc(primaryLogoSrc || null);
    setImageError(false);
    setImageLoading(true);
  }, [primaryLogoSrc]);

  // Create fallback initials
  const createInitials = (name: string) => {
    if (name.includes('Région')) {
      return 'RG';
    }
    if (name.includes('Communauté') || name.includes('CC')) {
      return 'CC';
    }
    if (name.includes('Chambre')) {
      return 'CI';
    }
    if (name.includes('Métropole')) {
      return 'MT';
    }

    const words = name.split(' ').filter(word =>
      word.length > 2 &&
      !['de', 'du', 'des', 'la', 'le', 'les', 'et', 'ou'].includes(word.toLowerCase())
    );

    return words.length >= 2
      ? (words[0][0] + words[1][0]).toUpperCase()
      : name.substring(0, 2).toUpperCase();
  };

  // Handle image load error with fallback logic
  const handleImageError = () => {
    if (fallbackLogoSrc && currentLogoSrc !== fallbackLogoSrc) {
      setCurrentLogoSrc(fallbackLogoSrc);
      setImageLoading(true);
      setImageError(false);
    } else {
      setImageError(true);
      setImageLoading(false);
    }
  };

  if (!currentLogoSrc || imageError) {
    return (
      <div className={`${sizeClasses[size]} bg-gradient-to-br from-slate-100 to-slate-200 rounded-lg flex items-center justify-center border border-slate-200 ${className}`}>
        <span className={`${textSizes[size]} font-bold text-slate-500`}>
          {createInitials(organizationName)}
        </span>
      </div>
    );
  }

  return (
    <div className={`${sizeClasses[size]} relative ${className}`}>
      {imageLoading && (
        <div className={`${sizeClasses[size]} bg-slate-100 rounded-lg animate-pulse absolute inset-0`} />
      )}
      <img
        src={currentLogoSrc}
        alt={`${organizationName} logo`}
        loading="lazy"
        decoding="async"
        className={`${sizeClasses[size]} object-contain rounded-lg transition-opacity duration-200 ${
          imageLoading ? 'opacity-0' : 'opacity-100'
        }`}
        onLoad={() => setImageLoading(false)}
        onError={handleImageError}
      />
    </div>
  );
};

export default OrganizationLogo;
